language: node_js
node_js:
   - 14

deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY 
    bucket: "duocun-log-api"
    region: us-east-1

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "duocun-log-api"
    key: latest/MyApp.zip
    application: "duocun-log-api"
    deployment_group: "duocun-deploy-group"
    region: us-east-1
