language: node_js
node_js:
   - 14

cache:
    directories:
        - node_modules
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: dpl_cd_upload 
    skip_cleanup: true
    repo: duocun/duocun-log-api
    bucket: "duocun-log-api"
    region: us-east-1
    on: &2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "duocun-log-api"
    key: latest.zip
    bundle_type: zip
    application: "duocun-log-api"
    deployment_group: "duocun-deploy-group"
    region: us-east-1
    on: *2

script:
    - zip -r latest *
    - mkdir -p dpl_cd_upload
    - mv latest.zip dpl_cd_upload/latest.zip
